Remove .rubocop.yml Rails/DefaultScope config due to obsoletion
Fixes error:
 > Error: The `Rails/DefaultScope` cop no longer exists.
 > (obsolete configuration found in administrate/.rubocop.yml,
 > please update it)