Looks like explicit type is needed after all
```
NoMethodError:
undefined method `render' for #<RSpec::ExampleGroups::FieldsTextForm "doesn't require input options" (./spec/administrate/views/fields/text/_form_spec.rb:18)>
```

https://github.com/thoughtbot/administrate/actions/runs/11098287221/job/30909674170?pr=2665