Fix generator for non-association/columnar attrs.
Rails allows for custom attributes, and these are often used with gems
such as `attr_encrypted`. Previously, the Dashboard generator would fail
with:

> undefined method `has_one?' for nil:NilClass (NoMethodError)

Instead of failing with an error, this ensures we rely on column names
instead of attributes names.